<script setup lang="ts">
import { ElMessage } from 'element-plus'
definePageMeta({ layout: 'admin' })
const authFetch = useAuthFetch()
const search = ref(''); const statusFilter = ref(''); const visibilityFilter = ref('')
const { data, status, error, refresh } = await useAsyncData('admin-photos', () => authFetch<any>('/api/photos', { query: { limit: 100, ...(statusFilter.value ? { status: statusFilter.value } : {}) } }), { watch: [statusFilter] })
const photos = computed(() => (data.value?.photos || []).filter((p:any) => { const q=search.value.trim().toLowerCase(); return (!q || `${p.title} ${p.filename}`.toLowerCase().includes(q)) && (!visibilityFilter.value || p.visibility === visibilityFilter.value) }))
const busy = ref<number|null>(null)
const labels:Record<string,string> = { published:'已发布', hidden:'已隐藏', archived:'已归档', public:'公开', friends:'好友可见', private:'私密', pending:'待处理', approved:'已通过', rejected:'已拒绝', local:'本地', synced:'已同步' }
function label(v:string){ return labels[v] || v || '—' }
async function updatePhoto(photo:any, field:'status'|'visibility', value:string){ busy.value=photo.id; try { await authFetch(`/api/photos/${photo.id}`, { method:'PATCH', body:{ [field]:value } }); photo[field]=value; ElMessage.success('照片设置已更新') } catch(e:any){ ElMessage.error(e?.data?.message || '更新失败') } finally { busy.value=null } }
</script>
<template>
  <div class="photo-admin">
    <div class="page-header"><div><div class="eyebrow">MEDIA / CONTROL ROOM</div><h2>照片管理</h2><p>集中查看照片状态、可见范围和同步信息。修改会立即影响前台展示。</p></div><el-button @click="refresh">刷新</el-button></div>
    <el-alert class="hint" title="怎么使用？" description="相册负责组织照片；这里负责单张照片的发布、隐藏和可见范围。需要把照片放进某个相册，请进入相册管理。" type="info" show-icon :closable="false" />
    <div class="toolbar"><div class="search"><span>⌕</span><el-input v-model="search" placeholder="搜索标题或文件名" clearable /></div><el-select v-model="statusFilter" placeholder="展示状态" clearable><el-option label="已发布" value="published" /><el-option label="已隐藏" value="hidden" /><el-option label="已归档" value="archived" /></el-select><el-select v-model="visibilityFilter" placeholder="可见范围" clearable><el-option label="公开" value="public" /><el-option label="好友可见" value="friends" /><el-option label="私密" value="private" /></el-select><span class="total">{{ photos.length }} 张</span></div>
    <el-alert v-if="error" type="error" :title="error.message" show-icon />
    <div v-loading="status === 'pending'" class="table-wrap"><el-table :data="photos" stripe><el-table-column label="预览" width="92"><template #default="{ row }"><img class="thumb" :src="row.thumbnailUrl || row.mediumUrl || row.originalUrl" :alt="row.title" /></template></el-table-column><el-table-column prop="title" label="照片" min-width="190"><template #default="{ row }"><div class="photo-title">{{ row.title }}</div><div class="filename">{{ row.filename }}</div></template></el-table-column><el-table-column label="展示状态" width="150"><template #default="{ row }"><el-select :model-value="row.status" size="small" :loading="busy === row.id" @change="(v:string)=>updatePhoto(row,'status',v)"><el-option v-for="v in ['published','hidden','archived']" :key="v" :label="label(v)" :value="v" /></el-select></template></el-table-column><el-table-column label="可见范围" width="150"><template #default="{ row }"><el-select :model-value="row.visibility" size="small" :loading="busy === row.id" @change="(v:string)=>updatePhoto(row,'visibility',v)"><el-option v-for="v in ['public','friends','private']" :key="v" :label="label(v)" :value="v" /></el-select></template></el-table-column><el-table-column label="审核 / 同步" width="150"><template #default="{ row }"><div>{{ label(row.reviewStatus) }}</div><div class="subtle">{{ label(row.syncStatus) }}</div></template></el-table-column><el-table-column label="所在相册" min-width="180"><template #default="{ row }"><div v-if="row.albums?.length" class="album-links"><NuxtLink v-for="item in row.albums" :key="item.albumId" :to="`/admin/albums/${item.albumId}`">{{ item.album?.name }}</NuxtLink></div><span v-else class="subtle">未加入相册</span></template></el-table-column></el-table><el-empty v-if="status !== 'pending' && !photos.length" description="没有符合条件的照片" /></div>
  </div>
</template>
<style scoped>
.photo-admin{width:100%}.page-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.eyebrow{font:11px var(--font-mono);letter-spacing:.12em;color:var(--color-primary);margin-bottom:8px}.page-header h2{margin:0 0 6px;font-size:1.6rem}.page-header p{margin:0;color:var(--color-text-secondary)}.hint{margin-bottom:18px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:16px}.search{display:flex;align-items:center;gap:6px;flex:1;min-width:240px}.search>span{color:var(--color-primary);font-size:1.3rem}.total{margin-left:auto;color:var(--color-text-muted);font:12px var(--font-mono)}.table-wrap{background:#fff;border:1px solid var(--color-border);border-radius:10px;padding:4px 12px 18px}.thumb{width:58px;height:46px;display:block;object-fit:cover;border-radius:6px;background:var(--color-bg-secondary)}.photo-title{font-weight:600}.filename,.subtle{font-size:12px;color:var(--color-text-muted)}.album-links{display:flex;flex-wrap:wrap;gap:5px}.album-links a{color:var(--color-primary);text-decoration:none}.album-links a:hover{text-decoration:underline}@media(max-width:700px){.page-header{gap:14px;flex-direction:column}.table-wrap{overflow:auto}}
</style>
