<script setup lang="ts">
const router = useRouter(); const route = useRoute(); const collapsed = ref(false)
const user = ref<any>(null)
onMounted(() => { try { user.value = JSON.parse(localStorage.getItem('user') || 'null') } catch {} })
const menu = [
  ['/admin', '仪表盘'], ['/admin/articles', '文章管理'], ['/admin/photos', '照片管理'], ['/admin/albums', '相册管理'],
  ['/admin/users', '用户管理'], ['/admin/storage', '存储管理'], ['/admin/audit', '审计日志'], ['/admin/content-pipeline', '内容流水线'], ['/admin/hermes', 'AI 与技能'],
]
function logout() { localStorage.removeItem('token'); localStorage.removeItem('user'); router.push('/admin/login') }
</script>
<template><el-container class="layout"><el-aside :width="collapsed ? '70px' : '220px'" class="aside"><div class="brand" @click="router.push('/admin')">{{ collapsed ? 'P' : '个人站点管理' }}</div><el-menu :default-active="route.path" class="menu" @select="(path) => router.push(path)"><el-menu-item v-for="([path, label]) in menu" :key="path" :index="path"><span>{{ collapsed ? label.slice(0, 1) : label }}</span></el-menu-item></el-menu><button class="collapse" @click="collapsed = !collapsed">{{ collapsed ? '展开' : '收起' }}</button></el-aside><el-container><el-header class="header"><el-breadcrumb><el-breadcrumb-item :to="{ path: '/admin' }">管理后台</el-breadcrumb-item><el-breadcrumb-item v-if="route.path !== '/admin'">{{ menu.find(item => item[0] === route.path)?.[1] || '页面' }}</el-breadcrumb-item></el-breadcrumb><div class="header-actions"><span v-if="user">{{ user.name || user.username }}</span><el-button text @click="router.push('/')">查看前台</el-button><el-button text type="danger" @click="logout">退出登录</el-button></div></el-header><el-main class="main"><slot /></el-main></el-container></el-container></template>
<style scoped>.layout{min-height:100vh}.aside{background:#1f2937;color:#fff;display:flex;flex-direction:column}.brand{padding:22px 18px;font-weight:700;border-bottom:1px solid #374151;cursor:pointer;white-space:nowrap}.menu{flex:1;border:0;background:transparent}.menu :deep(.el-menu-item){color:#cbd5e1}.menu :deep(.el-menu-item.is-active),.menu :deep(.el-menu-item:hover){background:#374151;color:#fff}.collapse{border:0;border-top:1px solid #374151;background:transparent;color:#cbd5e1;padding:14px;cursor:pointer}.header{height:60px;border-bottom:1px solid #e5e7eb;background:#fff;display:flex;align-items:center;justify-content:space-between}.header-actions{display:flex;align-items:center;gap:12px;color:#606266}.main{background:#f6f7f9;padding:24px}</style>
