<script setup lang="ts">
definePageMeta({ layout: 'admin' })
const route = useRoute(); const router = useRouter(); const authFetch = useAuthFetch(); const id = String(route.params.id)
const { data, status, error, refresh } = await useAsyncData(`admin-portfolio-${id}`, () => authFetch<any>(`/api/admin/portfolio/${id}`))
const item = computed(() => data.value?.data)
const form = reactive<any>({ title: '', slug: '', description: '', type: 'project', displayStatus: 'experiment', year: undefined, location: '', featured: false, order: 0, version: 1 })
const rolesText = ref(''); const techText = ref(''); const mediumText = ref(''); const tagsText = ref('')
const mediaForm = reactive<any>({ kind: 'image', publicUrl: '', alt: '', caption: '', status: 'draft', width: null, height: null, duration: null, posterUrl: '', sortOrder: 0 })
const blockForm = reactive<any>({ kind: 'richText', title: '', anchor: '', payloadText: '{"markdown":""}', visibility: 'draft', sortOrder: 0 })
const promptForm = reactive<any>({ title: '', slug: '', category: '', summary: '', body: '', riskLevel: 'low', status: 'draft', tags: [] })
const uploadInput = ref<HTMLInputElement | null>(null)
function parseList(value: string | null) { try { const v = JSON.parse(value || '[]'); return Array.isArray(v) ? v : [] } catch { return (value || '').split(',').map((x) => x.trim()).filter(Boolean) } }
watch(item, (value) => { if (!value) return; Object.assign(form, { title: value.title, slug: value.slug, description: value.description || '', type: value.type || 'project', displayStatus: value.displayStatus || 'experiment', year: value.year || undefined, location: value.location || '', featured: value.featured, order: value.order, version: value.version }); rolesText.value = parseList(value.rolesJson).join(', '); techText.value = parseList(value.techStackJson).join(', '); mediumText.value = parseList(value.mediumJson).join(', '); tagsText.value = value.tags || '' }, { immediate: true })
const saving = ref(false)
async function save() { saving.value = true; try { const result: any = await authFetch(`/api/admin/portfolio/${id}`, { method: 'PUT', body: { ...form, roles: rolesText.value.split(',').map((x) => x.trim()).filter(Boolean), techStack: techText.value.split(',').map((x) => x.trim()).filter(Boolean), medium: mediumText.value.split(',').map((x) => x.trim()).filter(Boolean), tags: tagsText.value.split(',').map((x) => x.trim()).filter(Boolean) } }); form.version = result.data.version; ElMessage.success('草稿已保存'); await refresh() } catch (e: any) { ElMessage.error(e?.data?.message || '保存失败') } finally { saving.value = false } }
async function transition(action: string, body: any = {}) { try { await authFetch(`/api/admin/portfolio/${id}/${action}`, { method: 'POST', body }); ElMessage.success('状态已更新'); await refresh() } catch (e: any) { ElMessage.error(e?.data?.message || '状态操作失败') } }
async function addMedia() { try { await authFetch(`/api/admin/portfolio/${id}/media`, { method: 'POST', body: mediaForm }); ElMessage.success('媒体已关联'); Object.assign(mediaForm, { publicUrl: '', alt: '', caption: '', width: null, height: null, duration: null, posterUrl: '' }); await refresh() } catch (e: any) { ElMessage.error(e?.data?.message || '媒体关联失败') } }
async function addBlock() { try { const payload = JSON.parse(blockForm.payloadText || '{}'); await authFetch(`/api/admin/portfolio/${id}/blocks`, { method: 'POST', body: { ...blockForm, payload } }); ElMessage.success('区块已保存'); blockForm.payloadText = '{"markdown":""}'; await refresh() } catch (e: any) { ElMessage.error(e?.data?.message || '区块 JSON 或保存失败') } }
async function addPrompt() { try { await authFetch(`/api/admin/portfolio/${id}/prompt-entries`, { method: 'POST', body: promptForm }); ElMessage.success('提示词条目已保存'); Object.assign(promptForm, { title: '', slug: '', category: '', summary: '', body: '' }); await refresh() } catch (e: any) { ElMessage.error(e?.data?.message || '提示词保存失败') } }
async function uploadMedia() { const file = uploadInput.value?.files?.[0]; if (!file) return ElMessage.warning('请选择媒体文件'); const body = new FormData(); body.append('file', file); body.append('alt', mediaForm.alt); if (mediaForm.posterUrl) body.append('posterUrl', mediaForm.posterUrl); if (mediaForm.width) body.append('width', String(mediaForm.width)); if (mediaForm.height) body.append('height', String(mediaForm.height)); if (mediaForm.duration) body.append('duration', String(mediaForm.duration)); body.append('sortOrder', String(mediaForm.sortOrder || 0)); try { await authFetch(`/api/admin/portfolio/${id}/media/upload`, { method: 'POST', body }); ElMessage.success('文件已上传，等待媒体处理完成后再发布'); if (uploadInput.value) uploadInput.value.value = ''; await refresh() } catch (e: any) { ElMessage.error(e?.data?.message || '媒体上传失败') } }
async function archive() { await ElMessageBox.confirm('归档后作品将从公开列表隐藏，但内容和审计记录会保留。', '确认归档', { type: 'warning' }).then(() => transition('archive')).catch(() => {}) }
</script>

<template>
  <section class="portfolio-editor">
    <div v-if="status === 'pending'"><el-skeleton :rows="12" animated /></div>
    <el-result v-else-if="error || !item" icon="warning" title="作品不存在" sub-title="请返回作品管理列表重新选择"><template #extra><el-button @click="router.push('/admin/portfolio')">返回列表</el-button></template></el-result>
    <template v-else>
      <header class="page-header"><div><NuxtLink class="back" to="/admin/portfolio">← 返回作品管理</NuxtLink><p class="kicker">PORTFOLIO / EDITOR</p><h1>{{ item.title }}</h1><p>保存草稿后再送审；所有公开内容会经过服务端发布检查。</p></div><div class="actions"><el-button :loading="saving" type="primary" @click="save">保存草稿</el-button><el-button v-if="item.status === 'draft' && ['pending','changes_requested'].includes(item.reviewStatus)" @click="transition('submit')">送审</el-button><el-button v-if="item.reviewStatus === 'submitted'" @click="transition('review', { action: 'approve' })">批准</el-button><el-button v-if="item.reviewStatus === 'approved' && item.status === 'draft'" type="success" @click="transition('publish')">公开发布</el-button><el-button v-if="item.status === 'published'" @click="transition('unpublish')">撤回公开</el-button><el-button v-if="item.status !== 'archived'" type="danger" plain @click="archive">归档</el-button></div></header>
      <div class="status-strip"><span>发布：<b>{{ item.status }}</b></span><span>审核：<b>{{ item.reviewStatus }}</b></span><span>版本：<b>{{ item.version }}</b></span><span v-if="item.reviewNote">审核意见：{{ item.reviewNote }}</span></div>
      <div class="editor-grid"><form class="form-surface" @submit.prevent="save"><h2>基础信息</h2><div class="field-grid"><label>标题<input v-model="form.title" required /></label><label>Slug<input v-model="form.slug" required /></label><label>类型<select v-model="form.type"><option value="project">项目 / 实验</option><option value="visual">视觉 / 影像</option><option value="tool">工具 / 仓库</option></select></label><label>访客状态<select v-model="form.displayStatus"><option value="in_progress">进行中</option><option value="completed">已完成</option><option value="experiment">实验</option><option value="archived">归档</option></select></label><label>年份<input v-model.number="form.year" type="number" min="1900" max="2200" /></label><label>地点<input v-model="form.location" /></label></div><label>简介<textarea v-model="form.description" rows="4" maxlength="2000" /></label><div class="field-grid"><label>角色<input v-model="rolesText" placeholder="设计, 开发" /></label><label>技术栈<input v-model="techText" placeholder="Nuxt, Vue" /></label><label>媒介<input v-model="mediumText" placeholder="图文, 代码" /></label><label>标签<input v-model="tagsText" placeholder="webgl, experiment" /></label></div><label class="check"><input v-model="form.featured" type="checkbox" /> 设为精选作品</label></form><aside class="side-panel"><h2>发布检查</h2><p>服务端会检查封面/预览媒体、摘要、类型、区块、资源和提示词状态。</p><dl><div><dt>类型</dt><dd>{{ form.type }}</dd></div><div><dt>资源</dt><dd>{{ item.resources?.length || 0 }}</dd></div><div><dt>媒体</dt><dd>{{ item.media?.length || 0 }}</dd></div><div><dt>区块</dt><dd>{{ item.blocks?.length || 0 }}</dd></div><div><dt>提示词</dt><dd>{{ item.promptEntries?.length || 0 }}</dd></div></dl></aside></div>
      <div class="nested-grid"><section class="form-surface"><h2>媒体关联</h2><div class="field-grid"><label>类型<select v-model="mediaForm.kind"><option value="cover">封面</option><option value="image">图片</option><option value="video">视频</option><option value="gif">GIF</option></select></label><label>URL<input v-model="mediaForm.publicUrl" required /></label><label>Alt<input v-model="mediaForm.alt" required /></label><label>图注<input v-model="mediaForm.caption" /></label></div><el-button plain type="primary" @click="addMedia">关联媒体</el-button><ul class="asset-list"><li v-for="media in item.media" :key="media.id">{{ media.kind }} · {{ media.status }} · {{ media.alt || '未填写 alt' }}</li></ul></section><section class="form-surface"><h2>内容区块</h2><div class="field-grid"><label>类型<select v-model="blockForm.kind"><option value="richText">叙事</option><option value="timeline">步骤线</option><option value="code">代码</option><option value="comparison">对比</option><option value="imageGallery">画廊</option><option value="embed">嵌入</option></select></label><label>标题<input v-model="blockForm.title" /></label><label>锚点<input v-model="blockForm.anchor" /></label><label>排序<input v-model.number="blockForm.sortOrder" type="number" min="0" /></label></div><textarea v-model="blockForm.payloadText" rows="6" /><el-button plain type="primary" @click="addBlock">保存区块</el-button><ul class="asset-list"><li v-for="block in item.blocks" :key="block.id">{{ block.kind }} · {{ block.title || '未命名' }}</li></ul></section></div>
      <section v-if="item.type === 'tool'" class="form-surface prompt-editor"><h2>PromptVault 条目</h2><div class="field-grid"><label>标题<input v-model="promptForm.title" required /></label><label>Slug<input v-model="promptForm.slug" required /></label><label>分类<input v-model="promptForm.category" /></label><label>摘要<input v-model="promptForm.summary" /></label></div><textarea v-model="promptForm.body" rows="8" placeholder="提示词正文" /><el-button plain type="primary" @click="addPrompt">保存条目</el-button><ul class="asset-list"><li v-for="entry in item.promptEntries" :key="entry.id">{{ entry.title }} · {{ entry.status }}</li></ul></section>
    </template>
  </section>
      <section class="form-surface media-upload-panel"><h2>媒体上传与处理</h2><p>支持受控图片和视频；服务端记录 MIME、大小、尺寸/时长与派生状态，未就绪媒体不会通过发布检查。</p><div class="field-grid"><label>文件<input ref="uploadInput" type="file" accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm,video/quicktime" /></label><label>Alt<input v-model="mediaForm.alt" required /></label><label>Poster URL<input v-model="mediaForm.posterUrl" /></label><label>宽度<input v-model.number="mediaForm.width" type="number" min="1" /></label><label>高度<input v-model.number="mediaForm.height" type="number" min="1" /></label><label>时长（秒）<input v-model.number="mediaForm.duration" type="number" min="0" /></label><label>章节排序<input v-model.number="mediaForm.sortOrder" type="number" min="0" /></label></div><el-button plain type="primary" @click="uploadMedia">上传媒体</el-button></section>
</template>

<style scoped>
.portfolio-editor{max-width:1280px}.page-header{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;margin-bottom:18px}.back{display:inline-block;margin-bottom:16px;color:#8edff1;font-size:12px;text-decoration:none}.kicker{margin:0 0 8px;color:#72d9ed;font:11px var(--font-mono);letter-spacing:.15em}.page-header h1{margin:0;color:#eff9fc;font-size:28px}.page-header p:not(.kicker){max-width:650px;margin:8px 0;color:#9eb5c2;font-size:13px;line-height:1.6}.actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap}.status-strip{display:flex;gap:20px;flex-wrap:wrap;margin-bottom:18px;padding:12px 14px;border:1px solid rgba(148,184,214,.2);border-radius:12px;background:rgba(14,26,42,.7);color:#9eb5c2;font-size:12px}.status-strip b{color:#dff8fc;font-family:var(--font-mono)}.editor-grid,.nested-grid{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:18px;margin-bottom:18px}.nested-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.form-surface,.side-panel{padding:22px;border:1px solid rgba(148,184,214,.2);border-radius:14px;background:rgba(14,26,42,.74)}h2{margin:0 0 18px;color:#e7f4f8;font-size:16px}.form-surface>label,.field-grid label{display:grid;gap:7px;margin-bottom:16px;color:#a9c0cb;font-size:12px}.field-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}.form-surface input,.form-surface textarea,.form-surface select{width:100%;border:1px solid rgba(148,184,214,.24);border-radius:9px;padding:10px 11px;background:rgba(5,14,25,.62);color:#e7f6fa;outline:none}.form-surface textarea{resize:vertical}.check{display:flex!important;align-items:center;gap:8px!important}.check input{width:auto!important;accent-color:#50c9e5}.side-panel p{margin:0 0 16px;color:#91a9b8;font-size:12px;line-height:1.7}.side-panel dl{margin:0;border-top:1px solid rgba(148,184,214,.15)}.side-panel dl div{display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid rgba(148,184,214,.12)}dt{color:#88a2b1;font-size:12px}dd{margin:0;color:#e6f6fa;font:12px var(--font-mono)}.asset-list{list-style:none;padding:0;margin:18px 0 0;border-top:1px solid rgba(148,184,214,.15)}.asset-list li{padding:10px 0;border-bottom:1px solid rgba(148,184,214,.12);color:#a9c0cb;font-size:12px}.prompt-editor{margin-bottom:18px}@media(max-width:850px){.page-header{flex-direction:column}.actions{justify-content:flex-start}.editor-grid,.nested-grid{grid-template-columns:1fr}.field-grid{grid-template-columns:1fr}}
</style>
